using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    /// <inheritdoc />
    public partial class ChangeRoleIdToInt : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // PostgreSQL cannot ALTER COLUMN from uuid to integer directly.
            // We must drop FKs, rebuild columns, and re-create constraints.

            // 1. Drop foreign keys that reference Roles.Id
            migrationBuilder.Sql("""
                ALTER TABLE "RoleFunctions" DROP CONSTRAINT IF EXISTS "FK_RoleFunctions_Roles_RoleId";
                ALTER TABLE "UserRoles" DROP CONSTRAINT IF EXISTS "FK_UserRoles_Roles_RoleId";
            """);

            // 2. Add temporary int id column to Roles with sequential values
            migrationBuilder.Sql("""
                ALTER TABLE "Roles" ADD COLUMN "NewId" integer GENERATED BY DEFAULT AS IDENTITY;
                UPDATE "Roles" SET "NewId" = nextval(pg_get_serial_sequence('"Roles"', 'NewId'));
            """);

            // 3. Update RoleFunctions.RoleId and UserRoles.RoleId to the new int values
            migrationBuilder.Sql("""
                ALTER TABLE "RoleFunctions" ADD COLUMN "NewRoleId" integer;
                UPDATE "RoleFunctions" rf SET "NewRoleId" = r."NewId"
                    FROM "Roles" r WHERE rf."RoleId" = r."Id";

                ALTER TABLE "UserRoles" ADD COLUMN "NewRoleId" integer;
                UPDATE "UserRoles" ur SET "NewRoleId" = r."NewId"
                    FROM "Roles" r WHERE ur."RoleId" = r."Id";
            """);

            // 4. Drop old uuid columns and PKs
            migrationBuilder.Sql("""
                ALTER TABLE "RoleFunctions" DROP CONSTRAINT IF EXISTS "PK_RoleFunctions";
                ALTER TABLE "UserRoles" DROP CONSTRAINT IF EXISTS "PK_UserRoles";
                ALTER TABLE "Roles" DROP CONSTRAINT IF EXISTS "PK_Roles";

                ALTER TABLE "RoleFunctions" DROP COLUMN "RoleId";
                ALTER TABLE "RoleFunctions" RENAME COLUMN "NewRoleId" TO "RoleId";
                ALTER TABLE "RoleFunctions" ALTER COLUMN "RoleId" SET NOT NULL;

                ALTER TABLE "UserRoles" DROP COLUMN "RoleId";
                ALTER TABLE "UserRoles" RENAME COLUMN "NewRoleId" TO "RoleId";
                ALTER TABLE "UserRoles" ALTER COLUMN "RoleId" SET NOT NULL;

                ALTER TABLE "Roles" DROP COLUMN "Id";
                ALTER TABLE "Roles" RENAME COLUMN "NewId" TO "Id";
                ALTER TABLE "Roles" ALTER COLUMN "Id" SET NOT NULL;
            """);

            // 5. Recreate primary keys
            migrationBuilder.Sql("""
                ALTER TABLE "Roles" ADD CONSTRAINT "PK_Roles" PRIMARY KEY ("Id");
                ALTER TABLE "UserRoles" ADD CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId");
                ALTER TABLE "RoleFunctions" ADD CONSTRAINT "PK_RoleFunctions" PRIMARY KEY ("RoleId", "FunctionId");
            """);

            // 6. Recreate foreign keys
            migrationBuilder.Sql("""
                ALTER TABLE "UserRoles" ADD CONSTRAINT "FK_UserRoles_Roles_RoleId"
                    FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE;
                ALTER TABLE "RoleFunctions" ADD CONSTRAINT "FK_RoleFunctions_Roles_RoleId"
                    FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE;
            """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Drop FKs
            migrationBuilder.Sql("""
                ALTER TABLE "RoleFunctions" DROP CONSTRAINT IF EXISTS "FK_RoleFunctions_Roles_RoleId";
                ALTER TABLE "UserRoles" DROP CONSTRAINT IF EXISTS "FK_UserRoles_Roles_RoleId";
            """);

            // Revert Roles.Id back to uuid
            migrationBuilder.Sql("""
                ALTER TABLE "RoleFunctions" DROP CONSTRAINT IF EXISTS "PK_RoleFunctions";
                ALTER TABLE "UserRoles" DROP CONSTRAINT IF EXISTS "PK_UserRoles";
                ALTER TABLE "Roles" DROP CONSTRAINT IF EXISTS "PK_Roles";

                ALTER TABLE "Roles" DROP COLUMN "Id";
                ALTER TABLE "Roles" ADD COLUMN "Id" uuid NOT NULL DEFAULT gen_random_uuid();

                ALTER TABLE "UserRoles" DROP COLUMN "RoleId";
                ALTER TABLE "UserRoles" ADD COLUMN "RoleId" uuid NOT NULL DEFAULT gen_random_uuid();

                ALTER TABLE "RoleFunctions" DROP COLUMN "RoleId";
                ALTER TABLE "RoleFunctions" ADD COLUMN "RoleId" uuid NOT NULL DEFAULT gen_random_uuid();
            """);

            // Recreate PKs and FKs
            migrationBuilder.Sql("""
                ALTER TABLE "Roles" ADD CONSTRAINT "PK_Roles" PRIMARY KEY ("Id");
                ALTER TABLE "UserRoles" ADD CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId");
                ALTER TABLE "RoleFunctions" ADD CONSTRAINT "PK_RoleFunctions" PRIMARY KEY ("RoleId", "FunctionId");

                ALTER TABLE "UserRoles" ADD CONSTRAINT "FK_UserRoles_Roles_RoleId"
                    FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE;
                ALTER TABLE "RoleFunctions" ADD CONSTRAINT "FK_RoleFunctions_Roles_RoleId"
                    FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE;
            """);
        }
    }
}
