FROM node:22-alpine
WORKDIR /app

RUN apk add --no-cache libc6-compat

ENV NEXT_TELEMETRY_DISABLED=1

COPY --chown=node:node package.json package-lock.json ./

RUN chown -R node:node /app

USER node

RUN npm ci --legacy-peer-deps --no-audit --no-fund

COPY --chown=node:node . .

EXPOSE 3001

CMD ["npm", "run", "dev", "--", "-H", "0.0.0.0", "-p", "3001"]
