stages:
  - build
  - deploy

build-job:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - echo "Building..."
    - docker build -t panthora-be:latest . 
    
deploy:
  stage: deploy 
  only:
    - main
  image: docker:24.0.5    
  services:
    - docker:24.0.5-dind 
  script:
    - docker stop panthora || true
    - docker rm panthora || true
    - docker run -d --name panthora -p 8080:8080 panthora-be:latest
