stages:
  - build-and-deploy

deploy-app:
  stage: build-and-deploy
  tags:
    - do-an-fe
  only:
    - main
  script:
    - echo "Đang build Frontend..."
    - docker build -t pathora-fe:latest ./frontend
    - echo "Đang cập nhật các container qua Docker Compose..."
    - cd /home/huynqhe180309
    - touch .env
    - docker compose -f server_docker_compose.yml up -d