services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Default=Host=18.143.220.111;Port=5432;Database=Pathora;Username=root;Password=123abc@A
      - Redis__ConnectionString=redis:6379
      - MinIO__Endpoint=minio:9000
      - MinIO__AccessKey=minioadmin
      - MinIO__SecretKey=minioadmin123
      - MinIO__UseSSL=false
      - MinIO__DefaultBucket=panthora
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - redis
      - minio
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
