services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: src/Api/Dockerfile

  redis:
    image: redis:7-alpine

  minio:
    image: minio/minio:latest

  portainer:
    image: portainer/portainer-ce:latest

volumes:
  portainer_data:
