services:
  api:
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: "Host=34.87.55.176;Port=80;Database=Pathora;Username=postgres;Password=123abc@A"
      Redis__ConnectionString: "redis:6379"
      MinIO__Endpoint: "minio:9000"
      MinIO__PublicUrl: "http://localhost:9000"
      MinIO__AccessKey: "minioadmin"
      MinIO__SecretKey: "minioadmin123"
      MinIO__UseSSL: "false"
      MinIO__DefaultBucket: "panthora"
      Cors__AllowedOrigins__0: "http://localhost:3000"
      Cors__AllowedOrigins__1: "https://localhost:3000"
      Cors__AllowedOrigins__2: "http://localhost:4001"
      Cors__AllowedOrigins__3: "http://frontend:3000"

  frontend:
    ports:
      - "4001:3000"

  redis:
    ports:
      - "6379:6379"

  minio:
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console UI

  portainer:
    # UI: https://localhost:9443 or http://localhost:9002
    command:
      - --admin-password=$$2y$$05$$WhRrYB./WG4XqeLi2CxdkOKwhd55Lio1QHSKsGkRjcxze7PEWHEoe
    ports:
      - "9443:9443" # HTTPS UI
      - "9002:9000" # HTTP UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
